//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class users
    {
        public int uid { get; set; }
        [Required(ErrorMessage = "请输入用户名")]
        public string uname { get; set; }
        [Required(ErrorMessage = "请输入用户密码")]
        public string pwd { get; set; }
        public string sex { get; set; }
        public Nullable<int> age { get; set; }
        public System.DateTime birth { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
    }
}
